# Generated by Django 4.1.7 on 2023-03-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='unit',
            field=models.IntegerField(),
        ),
    ]
