# Generated by Django 4.1.7 on 2023-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_alter_reports_date_alter_reports_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
